version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=pegons"
      - "POSTGRES_DB=pegons"
      - "POSTGRES_PASSWORD=pegons"
    expose:
      - "5432"
    ports:
      - "5432:5432"